### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'content')

### ISSUE THREAD

**Issue by malle-pietje** [uccellolabs/filament-theme-color#1]
I've installed filament-theme-color through this starter kit by @rgasch:
https://github.com/rgasch/filament-extended-starter-kit

After a clean install I see these errors in the browser console:
```
Uncaught TypeError: Cannot read properties of null (reading 'content')
    at filament-theme-color-scripts.js:26:184
```

Any idea what could be causing this? I'm new to Filament (been using UserFrosting and BackPack for quite some time) but can help troubleshoot this.

**Comment by sardoj** [comment]
Hello,

It’s because in this starter kit the plug-in is not configured at all. 

Please follow the documentation to configure the package.

**Comment by malle-pietje** [comment]
Okay, thanks! I will submit a PR for the README file in his repo👍

**Comment by robertgdev** [comment]
I've fixed this issue and will release a new version of the starter kit tomorrow. Thank you!

**Comment by malle-pietje** [comment]
👍
